"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['tahoe-uri-handler.py']
OPTIONS = {
    'argv_emulation': False,
    'plist': {
        'CFBundleDevelopmentRegion': 'en',
        'NSPrincipalClass': 'NSApplication',
        'NSAppleScriptEnabled': 'YES',
        'LSUIElement': 'YES',
        'CFBundleIdentifier': 'io.peq.tahoe-handler',
        'CFBundleURLTypes': [{
            'CFBundleURLName': 'Tahoe-LAFS URI',
            'CFBundleURLSchemes': [
                'URI',
            ],
        }],
    }
}

setup(
    app=APP,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
